
 #  Probability

## PETE 2061 Lab 5

<a id='top'></a>

<a id='overview'></a>
# Topics Covered
<font color=blue>
 * [Itertools](#itertools) 
 * [Reading and saving csv files](#pandasio)
 * [Probability calculations](#probability)
</font>
<br>

<a id='itertools'></a>
## Itertools
The code below shows all the permutations of 3 strings A, B, C

In [2]:
import itertools
strList = ['A', 'B', 'C']
result = list(itertools.permutations(strList))
for item in result:
    print(item)

('A', 'B', 'C')
('A', 'C', 'B')
('B', 'A', 'C')
('B', 'C', 'A')
('C', 'A', 'B')
('C', 'B', 'A')

In [3]:
#What will this code print?
strList = ['A','B','C','D','E']
result = list(itertools.permutations(strList))
#resultLength = len(list(result)) #list() converts the itertools.permutations object to a list. len() gets the length of the list
#print(f"There are a total of {resultLength} permutations")
for item in result:
    print(item)

('A', 'B', 'C', 'D', 'E')
('A', 'B', 'C', 'E', 'D')
('A', 'B', 'D', 'C', 'E')
('A', 'B', 'D', 'E', 'C')
('A', 'B', 'E', 'C', 'D')
('A', 'B', 'E', 'D', 'C')
('A', 'C', 'B', 'D', 'E')
('A', 'C', 'B', 'E', 'D')
('A', 'C', 'D', 'B', 'E')
('A', 'C', 'D', 'E', 'B')
('A', 'C', 'E', 'B', 'D')
('A', 'C', 'E', 'D', 'B')
('A', 'D', 'B', 'C', 'E')
('A', 'D', 'B', 'E', 'C')
('A', 'D', 'C', 'B', 'E')
('A', 'D', 'C', 'E', 'B')
('A', 'D', 'E', 'B', 'C')
('A', 'D', 'E', 'C', 'B')
('A', 'E', 'B', 'C', 'D')
('A', 'E', 'B', 'D', 'C')
('A', 'E', 'C', 'B', 'D')
('A', 'E', 'C', 'D', 'B')
('A', 'E', 'D', 'B', 'C')
('A', 'E', 'D', 'C', 'B')
('B', 'A', 'C', 'D', 'E')
('B', 'A', 'C', 'E', 'D')
('B', 'A', 'D', 'C', 'E')
('B', 'A', 'D', 'E', 'C')
('B', 'A', 'E', 'C', 'D')
('B', 'A', 'E', 'D', 'C')
('B', 'C', 'A', 'D', 'E')
('B', 'C', 'A', 'E', 'D')
('B', 'C', 'D', 'A', 'E')
('B', 'C', 'D', 'E', 'A')
('B', 'C', 'E', 'A', 'D')
('B', 'C', 'E', 'D', 'A')
('B', 'D', 'A', 'C', 'E')
('B', 'D', 'A', 'E', 'C')
('B', 'D', 'C', 'A', 'E')
('B', 'D', 'C', 'E', 'A')
('B', 'D', 'E', 'A', 'C')
('B', 'D', 'E', 'C', 'A')
('B', 'E', 'A', 'C', 'D')
('B', 'E', 'A', 'D', 'C')
('B', 'E', 'C', 'A', 'D')
('B', 'E', 'C', 'D', 'A')
('B', 'E', 'D', 'A', 'C')
('B', 'E', 'D', 'C', 'A')
('C', 'A', 'B', 'D', 'E')
('C', 'A', 'B', 'E', 'D')
('C', 'A', 'D', 'B', 'E')
('C', 'A', 'D', 'E', 'B')
('C', 'A', 'E', 'B', 'D')
('C', 'A', 'E', 'D', 'B')
('C', 'B', 'A', 'D', 'E')
('C', 'B', 'A', 'E', 'D')
('C', 'B', 'D', 'A', 'E')
('C', 'B', 'D', 'E', 'A')
('C', 'B', 'E', 'A', 'D')
('C', 'B', 'E', 'D', 'A')
('C', 'D', 'A', 'B', 'E')
('C', 'D', 'A', 'E', 'B')
('C', 'D', 'B', 'A', 'E')
('C', 'D', 'B', 'E', 'A')
('C', 'D', 'E', 'A', 'B')
('C', 'D', 'E', 'B', 'A')
('C', 'E', 'A', 'B', 'D')
('C', 'E', 'A', 'D', 'B')
('C', 'E', 'B', 'A', 'D')
('C', 'E', 'B', 'D', 'A')
('C', 'E', 'D', 'A', 'B')
('C', 'E', 'D', 'B', 'A')
('D', 'A', 'B', 'C', 'E')
('D', 'A', 'B', 'E', 'C')
('D', 'A', 'C', 'B', 'E')
('D', 'A', 'C', 'E', 'B')
('D', 'A', 'E', 'B', 'C')
('D', 'A', 'E', 'C', 'B')
('D', 'B', 'A', 'C', 'E')
('D', 'B', 'A', 'E', 'C')
('D', 'B', 'C', 'A', 'E')
('D', 'B', 'C', 'E', 'A')
('D', 'B', 'E', 'A', 'C')
('D', 'B', 'E', 'C', 'A')
('D', 'C', 'A', 'B', 'E')
('D', 'C', 'A', 'E', 'B')
('D', 'C', 'B', 'A', 'E')
('D', 'C', 'B', 'E', 'A')
('D', 'C', 'E', 'A', 'B')
('D', 'C', 'E', 'B', 'A')
('D', 'E', 'A', 'B', 'C')
('D', 'E', 'A', 'C', 'B')
('D', 'E', 'B', 'A', 'C')
('D', 'E', 'B', 'C', 'A')
('D', 'E', 'C', 'A', 'B')
('D', 'E', 'C', 'B', 'A')
('E', 'A', 'B', 'C', 'D')
('E', 'A', 'B', 'D', 'C')
('E', 'A', 'C', 'B', 'D')
('E', 'A', 'C', 'D', 'B')
('E', 'A', 'D', 'B', 'C')
('E', 'A', 'D', 'C', 'B')
('E', 'B', 'A', 'C', 'D')
('E', 'B', 'A', 'D', 'C')
('E', 'B', 'C', 'A', 'D')
('E', 'B', 'C', 'D', 'A')
('E', 'B', 'D', 'A', 'C')
('E', 'B', 'D', 'C', 'A')
('E', 'C', 'A', 'B', 'D')
('E', 'C', 'A', 'D', 'B')
('E', 'C', 'B', 'A', 'D')
('E', 'C', 'B', 'D', 'A')
('E', 'C', 'D', 'A', 'B')
('E', 'C', 'D', 'B', 'A')
('E', 'D', 'A', 'B', 'C')
('E', 'D', 'A', 'C', 'B')
('E', 'D', 'B', 'A', 'C')
('E', 'D', 'B', 'C', 'A')
('E', 'D', 'C', 'A', 'B')
('E', 'D', 'C', 'B', 'A')

** In how many ways can 3 lifeguards be chosen and ordered among the stations?**

In [4]:
strList = ['A','B','C','D','E']
result = itertools.permutations(strList,3) #The second argument of the function specifies number of objects to select
resultLength = len(list(result)) 
print(f"The total number of permutations of 3 lifeguards chosen from 5 is {resultLength}")
list(itertools.permutations(strList,3))

The total number of permutations of 3 lifeguards chosen from 5 is 60

[('A', 'B', 'C'),
 ('A', 'B', 'D'),
 ('A', 'B', 'E'),
 ('A', 'C', 'B'),
 ('A', 'C', 'D'),
 ('A', 'C', 'E'),
 ('A', 'D', 'B'),
 ('A', 'D', 'C'),
 ('A', 'D', 'E'),
 ('A', 'E', 'B'),
 ('A', 'E', 'C'),
 ('A', 'E', 'D'),
 ('B', 'A', 'C'),
 ('B', 'A', 'D'),
 ('B', 'A', 'E'),
 ('B', 'C', 'A'),
 ('B', 'C', 'D'),
 ('B', 'C', 'E'),
 ('B', 'D', 'A'),
 ('B', 'D', 'C'),
 ('B', 'D', 'E'),
 ('B', 'E', 'A'),
 ('B', 'E', 'C'),
 ('B', 'E', 'D'),
 ('C', 'A', 'B'),
 ('C', 'A', 'D'),
 ('C', 'A', 'E'),
 ('C', 'B', 'A'),
 ('C', 'B', 'D'),
 ('C', 'B', 'E'),
 ('C', 'D', 'A'),
 ('C', 'D', 'B'),
 ('C', 'D', 'E'),
 ('C', 'E', 'A'),
 ('C', 'E', 'B'),
 ('C', 'E', 'D'),
 ('D', 'A', 'B'),
 ('D', 'A', 'C'),
 ('D', 'A', 'E'),
 ('D', 'B', 'A'),
 ('D', 'B', 'C'),
 ('D', 'B', 'E'),
 ('D', 'C', 'A'),
 ('D', 'C', 'B'),
 ('D', 'C', 'E'),
 ('D', 'E', 'A'),
 ('D', 'E', 'B'),
 ('D', 'E', 'C'),
 ('E', 'A', 'B'),
 ('E', 'A', 'C'),
 ('E', 'A', 'D'),
 ('E', 'B', 'A'),
 ('E', 'B', 'C'),
 ('E', 'B', 'D'),
 ('E', 'C', 'A'),
 ('E', 'C', 'B'),
 ('E', 'C', 'D'),
 ('E', 'D', 'A'),
 ('E', 'D', 'B'),
 ('E', 'D', 'C')]

**The number of ways of choosing any 3 lifeguards from a group of 5 life guards**

In [6]:
strList = ['A','B','C','D','E']
resultList = list(itertools.combinations(strList,3)) #The second argument of the function specifies number of objects to select
print(f"The total number of ways of choosing 3 lifeguards from 5 is {len(resultList)}")

#You can store all of these outcomes in a pandas DataFrame as shown below:
import pandas as pd
df = pd.DataFrame({'outcomes':resultList})
df

The total number of ways of choosing 3 lifeguards from 5 is 10

    outcomes
0  (A, B, C)
1  (A, B, D)
2  (A, B, E)
3  (A, C, D)
4  (A, C, E)
5  (A, D, E)
6  (B, C, D)
7  (B, C, E)
8  (B, D, E)
9  (C, D, E)

<a id='pandasio'></a>
### Reading and Saving csv files
* You can read a csv file directly into a Pandas DataFrame using the funtion pd.read_csv()
* You can save a Pandas DataFrame into a csv file using the function df.to_csv()

In [6]:
df.to_csv('outcomes.csv',index=False)

In [7]:
inputDF = pd.read_csv('outcomes.csv')
inputDF

          outcomes
0  ('A', 'B', 'C')
1  ('A', 'B', 'D')
2  ('A', 'B', 'E')
3  ('A', 'C', 'D')
4  ('A', 'C', 'E')
5  ('A', 'D', 'E')
6  ('B', 'C', 'D')
7  ('B', 'C', 'E')
8  ('B', 'D', 'E')
9  ('C', 'D', 'E')

<a id='probability'></a>
## Probability Calculations
* The first example below shows how to count the total number of outcomes of rolling a die once

In [7]:
numList = list(range(1,7)) #gives a list from 1 to 6 representing the total sample space
resultList = list(itertools.combinations(numList,1)) #This does 6 Combination 1, to basically choose 1 out of 6 outcomes
#resultList = list(itertools.permutations(numList,1)) #Gives same result as combinations when choosing just 1.
print(f"Total number of outcomes = {len(resultList)}")
print(resultList)

Total number of outcomes = 6
[(1,), (2,), (3,), (4,), (5,), (6,)]

**The code below illustrates how to compute the probabililities of all possible total values that can be obtained from rolling a fair die two times (or rolling two fair dice)**

In [11]:
numList = list(range(1,7))
resultList1 = list(itertools.product(numList,repeat=2)) #this is how we simulate rolling the die twice (or rolling 2 dice)
print(f"Total number of outcomes = {len(resultList1)}")
#print(resultList1)

import numpy as np
resultArray = np.array(resultList1)
sumOutcomes = np.sum(resultArray, axis=1)

df1 = pd.DataFrame({"outcomes":resultList1,"sumOutcomes":sumOutcomes})
df1

Total number of outcomes = 36

   outcomes  sumOutcomes
0    (1, 1)            2
1    (1, 2)            3
2    (1, 3)            4
3    (1, 4)            5
4    (1, 5)            6
5    (1, 6)            7
6    (2, 1)            3
7    (2, 2)            4
8    (2, 3)            5
9    (2, 4)            6
10   (2, 5)            7
11   (2, 6)            8
12   (3, 1)            4
13   (3, 2)            5
14   (3, 3)            6
15   (3, 4)            7
16   (3, 5)            8
17   (3, 6)            9
18   (4, 1)            5
19   (4, 2)            6
20   (4, 3)            7
21   (4, 4)            8
22   (4, 5)            9
23   (4, 6)           10
24   (5, 1)            6
25   (5, 2)            7
26   (5, 3)            8
27   (5, 4)            9
28   (5, 5)           10
29   (5, 6)           11
30   (6, 1)            7
31   (6, 2)            8
32   (6, 3)            9
33   (6, 4)           10
34   (6, 5)           11
35   (6, 6)           12

In [23]:
by_sumOutcomes = df1.groupby("sumOutcomes")
by_sumOutcomes.describe()
outcomeDF = by_sumOutcomes.count()
outcomes = outcomeDF.values[:,0]
probability = outcomes / np.sum(outcomes)
newDF = pd.DataFrame({"sum":df1["sumOutcomes"].unique(), "outcomes":outcomes, "probability":probability})
newDF

    sum  outcomes  probability
0     2         1     0.027778
1     3         2     0.055556
2     4         3     0.083333
3     5         4     0.111111
4     6         5     0.138889
5     7         6     0.166667
6     8         5     0.138889
7     9         4     0.111111
8    10         3     0.083333
9    11         2     0.055556
10   12         1     0.027778

** Exercise: Repeat this calculation for 3 dice **
** Exercise: Repeat this calculation for 4 coins **